# Generated by Django 4.2.6 on 2023-11-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'Trocar válvula do motor'), ('TO', 'Troca de óleo'), ('TF', 'Troca de freio'), ('TP', 'Troca de pneus'), ('TA', 'Troca de amortecedor'), ('B', 'Balanceamento')], max_length=3),
        ),
    ]
